import {
  Plug,
  Car,
  BatteryCharging,
  Cable,
  Video,
  Camera,
  Wifi,
  HardDrive,
  Sun,
  Zap,
  Battery,
  Package,
  Router,
  Network,
  Signal,
  Wrench,
  Building2,
  Globe2,
  Users,
  Send,
  Landmark,
  Stethoscope,
  Factory,
  Fuel,
  Shirt,
  GraduationCap,
  ShieldCheck,
  Radio,
  Headset,
  ShieldAlert,
  MonitorCog,
  type LucideProps,
} from "lucide-react";

const iconMap = {
  plug: Plug,
  car: Car,
  "battery-charging": BatteryCharging,
  cable: Cable,
  video: Video,
  camera: Camera,
  wifi: Wifi,
  "hard-drive": HardDrive,
  sun: Sun,
  zap: Zap,
  battery: Battery,
  package: Package,
  router: Router,
  network: Network,
  signal: Signal,
  wrench: Wrench,
  building: Building2,
  globe: Globe2,
  users: Users,
  send: Send,
  landmark: Landmark,
  stethoscope: Stethoscope,
  factory: Factory,
  fuel: Fuel,
  shirt: Shirt,
  "graduation-cap": GraduationCap,
  "shield-check": ShieldCheck,
  radio: Radio,
  headset: Headset,
  "shield-alert": ShieldAlert,
  "monitor-cog": MonitorCog,
} as const;

export type IconName = keyof typeof iconMap;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = iconMap[name];
  return <Component {...props} />;
}
