import {
  Plug,
  Car,
  BatteryCharging,
  Cable,
  Video,
  Camera,
  Wifi,
  HardDrive,
  Sun,
  Zap,
  Battery,
  Package,
  Router,
  Network,
  Signal,
  Wrench,
  Building2,
  Globe2,
  Users,
  Send,
  Landmark,
  Stethoscope,
  Factory,
  Fuel,
  Shirt,
  GraduationCap,
  ShieldCheck,
  Radio,
  Headset,
  ShieldAlert,
  MonitorCog,
  Truck,
  BadgeCheck,
  Smartphone,
  Laptop,
  Mouse,
  Briefcase,
  CircleHelp,
  Phone,
  Mail,
  MessageCircle,
  Target,
  Cpu,
  Monitor,
  MemoryStick,
  Projector,
  CircuitBoard,
  type LucideProps,
} from "lucide-react";

const iconMap = {
  plug: Plug,
  car: Car,
  "battery-charging": BatteryCharging,
  cable: Cable,
  video: Video,
  camera: Camera,
  wifi: Wifi,
  "hard-drive": HardDrive,
  sun: Sun,
  zap: Zap,
  battery: Battery,
  package: Package,
  router: Router,
  network: Network,
  signal: Signal,
  wrench: Wrench,
  building: Building2,
  globe: Globe2,
  users: Users,
  send: Send,
  landmark: Landmark,
  stethoscope: Stethoscope,
  factory: Factory,
  fuel: Fuel,
  shirt: Shirt,
  "graduation-cap": GraduationCap,
  "shield-check": ShieldCheck,
  radio: Radio,
  headset: Headset,
  "shield-alert": ShieldAlert,
  "monitor-cog": MonitorCog,
  truck: Truck,
  "badge-check": BadgeCheck,
  smartphone: Smartphone,
  laptop: Laptop,
  mouse: Mouse,
  briefcase: Briefcase,
  phone: Phone,
  mail: Mail,
  "message-circle": MessageCircle,
  target: Target,
  cpu: Cpu,
  monitor: Monitor,
  "memory-stick": MemoryStick,
  projector: Projector,
  "circuit-board": CircuitBoard,
} as const;

export type IconName = keyof typeof iconMap;

// `name` is typed as IconName, but values that ultimately come from the CMS
// only carry that type by assertion (see lib/cms.ts) — an editor picking an
// icon slug that isn't in iconMap yet (e.g. a field added before the
// matching frontend deploy) must not crash the page it renders on.
export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Component = iconMap[name] ?? CircleHelp;
  if (process.env.NODE_ENV !== "production" && !iconMap[name]) {
    console.warn(`[Icon] Unknown icon name "${name}" — falling back to a placeholder icon.`);
  }
  return <Component {...props} />;
}
